name: DMN_TCK_UPDATE
on:
  workflow_dispatch:
  schedule:
    - cron: '* 1 * * *'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Checkout TCK repo
      uses: actions/checkout@v6
      with:
        repository: dmn-tck/tck
        path: tmp/dmn-tck
    - name: Use Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Update TCK results
      run: npm run tck
      env:
        TCK_DIR: tmp/dmn-tck
        DRY_RUN: false
    - name: Generate API Token
      id: app-token
      uses: actions/create-github-app-token@v2
      with:
        app-id: ${{ secrets.TOKEN_APP_ID }}
        private-key: ${{ secrets.TOKEN_APP_KEY }}
    - name: Create TCK results update PR
      uses: peter-evans/create-pull-request@v8
      with:
        token: ${{ steps.app-token.outputs.token }}
        commit-message: |
          test(tck): update results
        branch: update-dmn-tck-status
        title: Update results of DMN TCK tests
        body: |
          ### Proposed changes

          Triggered by [this action](https://github.com/nikku/feelin/actions/runs/${{ github.run_id }}) this PR updates the DMN TCK test results.
